# Generated by Django 3.2.3 on 2021-05-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynvest_tube_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
