# Generated by Django 3.2.3 on 2021-05-30 19:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ynvest_tube_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 19, 13, 45, 551977, tzinfo=utc)),
        ),
    ]
