# Generated by Django 3.2.3 on 2021-05-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynvest_tube_app', '0002_auto_20210523_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dislikes',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
