# Generated by Django 3.2.3 on 2021-05-23 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynvest_tube_app', '0004_auction_video_views_on_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 20, 59, 14, 502011)),
        ),
        migrations.AddField(
            model_name='rent',
            name='state',
            field=models.TextField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], default='active'),
        ),
    ]
