# Generated by Django 3.2.3 on 2021-05-23 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynvest_tube_app', '0005_auto_20210523_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 21, 1, 29, 646671)),
        ),
    ]
