# Generated by Django 3.2.3 on 2021-05-26 19:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ynvest_tube_app', '0006_alter_auction_auction_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 19, 41, 41, 748849)),
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ynvest_tube_app.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ynvest_tube_app.user')),
            ],
        ),
    ]
