# Generated by Django 3.2.3 on 2021-05-29 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynvest_tube_app', '0007_auto_20210526_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='profit',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 18, 51, 8, 466474)),
        ),
    ]
