# Generated by Django 3.2.3 on 2021-05-29 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynvest_tube_app', '0008_auto_20210529_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 18, 57, 44, 129823)),
        ),
    ]
