swagger: "2.0"
info:
  version: 1.0.0
  title: YnvestTubeApi
host: "127.0.0.1:8000"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:

  /user:
    post:
      summary: "Get user's overall info cash, account creation date."
      tags:
        - user
      parameters:
        - in: body
          name: "UserId"
          required: true
          schema:
            $ref: '#/definitions/UserId'
      responses:
        '200':
          description: 'User data'
          schema:
            $ref: '#/definitions/User'
        '403':
          description: Bad user id

  /user/details:
    post:
      summary: "Get user's actual auctions and all rentals/ transactions."
      tags:
        - user
      parameters:
        - in: body
          name: "UserId"
          required: true
          schema:
            $ref: '#/definitions/UserId'
      responses:
        '200':
          description: 'User detailed data'
          schema:
            $ref: '#/definitions/UserDetails'
        '403':
          description: Bad user id

  /users/register:
    get:
      summary: "Register new user"
      tags:
        - user
      responses:
        "200":
          description: 'User id for an app to use in future calls'
          schema:
            $ref: '#/definitions/UserId'

  /auctions:
    post:
      summary: 'Get active and inactive auctions'
      tags:
        - auction
      parameters:
        - in: body
          name: "userid"
          schema:
            $ref: '#/definitions/UserId'
      responses:
        '200':
          description: 'Auction list retrieved successfully'
          schema:
            $ref: '#/definitions/Auctions'
        '405':
          description: Bad method

  /auctions/{auctionId}:
    post:
      summary: 'Get auction details'
      tags:
        - auction
      parameters:
        - in: path
          name: "auctionId"
          required: true
          type: integer
        - in: body
          name: "UserId"
          schema:
            $ref: '#/definitions/UserId'
      responses:
        '200':
          description: 'Auction retrieved successfully'
          schema:
            $ref: '#/definitions/Auction'
        '403':
          description: Bad auction id
    put:
      summary: 'Bid on auction'
      tags:
        - auction
      parameters:
        - in: path
          name: "auctionId"
          required: true
          type: integer
        - in: body
          name: "Bid"
          schema:
            $ref: '#/definitions/Bid'
      responses:
        '200':
          description: 'Bid successful'
          schema:
            $ref: '#/definitions/Auction'
        '400':
          description: Not enough value in bet
        '403':
          description: Bad user/auction id
        '404':
          description: Auction already ended


  /auctions/{auctionId}/close:
    delete:
      summary: 'Close auction'
      tags:
        - development
      parameters:
        - in: path
          name: "auctionId"
          required: true
          type: integer
      responses:
        '200':
          description: 'Auction closed successfully'
        '403':
          description: Bad auction id

  /users:
    get:
      summary: 'Get all users'
      tags:
        - development
      responses:
        '200':
          description: 'Users list retrieved successfully'
          schema:
            $ref: '#/definitions/UserList'
        '405':
          description: Bad method

  /rents:
    get:
      summary: 'Get all rents'
      tags:
        - development
      responses:
        '200':
          description: 'Rent list retrieved successfully'
          schema:
            $ref: '#/definitions/RentList'
        '405':
          description: Bad method


  /rents/insert-expired:
    post:
      summary: 'Assign expired rent to user'
      tags:
        - development
      responses:
        '200':
          description: 'Expired rent succesfully inserted'

        '405':
          description: Bad method

  /bids:
    get:
      summary: 'Get all bids'
      tags:
        - development
      responses:
        '200':
          description: 'Bids list retrieved successfully'
          schema:
            $ref: '#/definitions/BidList'
        '405':
          description: Bad method

  /videos:
    get:
      summary: 'Get all videos'
      tags:
        - development
      responses:
        '200':
          description: 'Videos list retrieved successfully'
          schema:
            $ref: '#/definitions/VideoList'
        '405':
          description: Bad method

  /videos/random-insert:
    put:
      summary: 'Insert multiple random youtube videos'
      tags:
        - development
      responses:
        '200':
          description: 'Videos succesfully inserted'
          schema:
            $ref: '#/definitions/UserList'
        '405':
          description: Bad method

definitions:
  UserId:
    type: object
    properties:
      UserId:
        type: string
        example: "729b8942-b579-11eb-8529-0242ac130003"

  User:
    type: object
    properties:
      id:
        type: string
      cash:
        type: integer
      creation_date:
        type: string

  UserDetails:
    type: object
    properties:
      attendingAuctions:
        type: array
        items:
          $ref: '#/definitions/Auction'
      actualRents:
        type: array
        items:
          $ref: '#/definitions/Rent'
      expiredRents:
        type: array
        items:
          $ref: '#/definitions/Rent'

  UserList:
    type: array
    items:
      $ref: '#/definitions/User'

  Auction:
    type: object
    properties:
      id:
        type: integer
      state:
        type: string
      starting_price:
        type: integer
      last_bid_value:
        type: integer
      user_contribution:
        type: integer
      video:
        $ref: '#/definitions/Video'
      rental_duration:
        type: string
      rental_expiration_date:
        type: string
      video_views_on_sold:
        type: integer

  Auctions:
    type: object
    properties:
      activeAuctions:
        type: array
        items:
          $ref: '#/definitions/Auction'
      inactiveAuctions:
        type: array
        items:
          $ref: '#/definitions/Auction'
  Rent:
    type: object
    properties:
      id:
        type: integer
      auction:
        $ref: '#/definitions/Auction'
      user:
        $ref: '#/definitions/User'
      state:
        type: string
      profit:
        type: integer

  RentList:
    type: array
    items:
      $ref: '#/definitions/Rent'

  BidList:
    type: array
    items:
      $ref: '#/definitions/Bid'

  Bid:
    type: object
    properties:
      UserId:
        type: string
      value:
        type: integer

  Video:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
      description:
        type: string
      link:
        type: string
      views:
        type: integer
      likes:
        type: integer
      dislikes:
        type: integer
      state:
        type: string

  VideoList:
    type: array
    items:
      $ref: '#/definitions/Video'